dataset: Pixel4DP
scene: "006"
batching: single_image
model: "lightfieldnerf"
factor: 0
num_coarse_samples: 64
num_fine_samples: 64
use_viewdirs: true
white_bkgd: true
batch_size: 4
randomized: true
lightfield_width: 8
lightfield_height: 8
num_rgb_channels: 1
render_every: 10000
near: 0.1
far: 4.0
max_steps: 40000
smoothness_loss_mult: 0.05
